#!/bin/bash

RUNNING=0
COMPILING=0
HEXING=0
FILENAME=""
while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        -r|--run)
            RUNNING=1
            shift
            ;;
        -c|--complie)
            COMPILING=1
            shift
            ;;
        -h|--hex)
            HEXING=1
            shift
            ;;
        *)
            FILENAME="$1"
            shift
            ;;
    esac
done

nasm $FILENAME -f bin -o boot.bin
if [[ $RUNNING -eq 1 ]]; then
    qemu-system-x86_64 boot.bin
elif [[ $COMPILING -eq 1 ]]; then
    :
elif [[ $HEXING -eq 1 ]]; then
    hexdump -C boot.bin
else
    echo "Unknown operation"
fi
